### ISSUE TITLE
User credentials are incorrect. Incorrect API key or IP address.

### ISSUE THREAD

**Issue by tubbynl** [bunq/tinker_java#10]
i found out my current sandbox-key didn't work anymore, support pointed me to you guys having a Tinker thingie 👍 

but i get the same exception trying to run the first statement (which i guess is the place to start), i guess i'm missing some sandbox-key-init step somewhere?

```
java -jar tinker/tinker.jar UserOverview

  ████████╗██╗███╗   ██╗██╗  ██╗███████╗██████╗ ██╗███╗   ██╗ ██████╗
  ╚══██╔══╝██║████╗  ██║██║ ██╔╝██╔════╝██╔══██╗██║████╗  ██║██╔════╝
     ██║   ██║██╔██╗ ██║█████╔╝ █████╗  ██████╔╝██║██╔██╗ ██║██║  ███╗
     ██║   ██║██║╚██╗██║██╔═██╗ ██╔══╝  ██╔══██╗██║██║╚██╗██║██║   ██║
     ██║   ██║██║ ╚████║██║  ██╗███████╗██║  ██║██║██║ ╚████║╚██████╔╝
     ╚═╝   ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝

Exception in thread "main" com.bunq.sdk.exception.BadRequestException: Response id to help bunq debug: 21e5a57d-0636-462a-b0ea-518322dccfa1. 
 Error message: User credentials are incorrect. Incorrect API key or IP address.
	at com.bunq.sdk.exception.ExceptionFactory.createExceptionForResponse(ExceptionFactory.java:40)
	at com.bunq.sdk.http.ApiClient.createApiExceptionRequestUnsuccessful(ApiClient.java:355)
	at com.bunq.sdk.http.ApiClient.assertResponseSuccess(ApiClient.java:336)
	at com.bunq.sdk.http.ApiClient.createBunqResponseRaw(ApiClient.java:312)
	at com.bunq.sdk.http.ApiClient.post(ApiClient.java:208)
	at com.bunq.sdk.model.core.DeviceServerInternal.create(DeviceServerInternal.java:21)
	at com.bunq.sdk.context.ApiContext.initializeDeviceRegistration(ApiContext.java:181)
	at com.bunq.sdk.context.ApiContext.initialize(ApiContext.java:164)
	at com.bunq.sdk.context.ApiContext.create(ApiContext.java:127)
	at com.bunq.sdk.context.ApiContext.create(ApiContext.java:109)
	at com.bunq.sdk.context.ApiContext.create(ApiContext.java:101)
	at com.bunq.tinker.libs.BunqLib.setupContext(BunqLib.java:91)
	at com.bunq.tinker.libs.BunqLib.<init>(BunqLib.java:79)
	at com.bunq.tinker.UserOverview.run(UserOverview.java:26)
	at com.bunq.tinker.utils.TinkerRunner.main(TinkerRunner.java:21)
```

**Comment by OGKevin** [comment]
@tubbynl Could you delete the `bunq-sandbox.conf` file and try running the command again.

**Comment by OGKevin** [comment]
This has to do with https://github.com/bunq/sdk_java/issues/89

**Comment by tubbynl** [comment]
just deleted the whole dir and retried the setup

```
macTub:bunq_tinker tubby$ java -jar tinker/tinker.jar UserOverview

  ████████╗██╗███╗   ██╗██╗  ██╗███████╗██████╗ ██╗███╗   ██╗ ██████╗
  ╚══██╔══╝██║████╗  ██║██║ ██╔╝██╔════╝██╔══██╗██║████╗  ██║██╔════╝
     ██║   ██║██╔██╗ ██║█████╔╝ █████╗  ██████╔╝██║██╔██╗ ██║██║  ███╗
     ██║   ██║██║╚██╗██║██╔═██╗ ██╔══╝  ██╔══██╗██║██║╚██╗██║██║   ██║
     ██║   ██║██║ ╚████║██║  ██╗███████╗██║  ██║██║██║ ╚████║╚██████╔╝
     ╚═╝   ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝

Exception in thread "main" com.bunq.sdk.exception.BunqException: timeout
	at com.bunq.tinker.libs.BunqLib.generateNewSandboxUser(BunqLib.java:263)
	at com.bunq.tinker.libs.BunqLib.setupContext(BunqLib.java:90)
	at com.bunq.tinker.libs.BunqLib.<init>(BunqLib.java:79)
	at com.bunq.tinker.UserOverview.run(UserOverview.java:26)
	at com.bunq.tinker.utils.TinkerRunner.main(TinkerRunner.java:21)
```

that will probably be the root-cause

**Comment by tubbynl** [comment]
but in general, i want to have some integration tests running against the sandbox; if this works i can probably use the bunq-sandbox.conf to run integrations tests with?

**Comment by OGKevin** [comment]
I just created a new dir and ran 

```
bash <(curl -s https://tinker.bunq.com/java/setup.sh)
```

then 

```
java -jar tinker/tinker.jar UserOverview
```

Whit-out any issues 🤔. And yes that should be no problem.

**Comment by tubbynl** [comment]
no, re-did that, i don't get the timeout now but the first exception still occurs.

where should the  bunq-sandbox.conf  be located? because it's not in the folder or any of it's subfolders, i can't find any .conf file there

**Comment by OGKevin** [comment]
OMG @tubbynl my apologies  :D I've made the release to soon x_X. Once https://github.com/bunq/tinker_java/pull/9 is merged  your issue should be fixed !

My apologies again.

**Comment by OGKevin** [comment]
@tubbynl please try again

**Comment by tubbynl** [comment]
re-created folder and ran setup again

now it works 👍

**Comment by tubbynl** [comment]
and the `bunq-sandbox.conf` is found at the root of the project when the init is succesfull

**Comment by OGKevin** [comment]
Thats nice to hear, ill close the issue then. Sorry for the inconvenience.
