### ISSUE TITLE
Certificate pinning failure

### ISSUE THREAD

**Issue by lvonk** [bunq/tinker_java#16]
Possibly related to https://github.com/bunq/tinker_java/pull/15

When running:

`java -jar tinker/tinker.jar UserOverview`

I get the following error:

> Exception in thread "main" com.bunq.sdk.exception.UncaughtExceptionError: Uncaught exception "Certificate pinning failure!
  Peer certificate chain:
    sha256/9Y+oZve6H+r17Kdn+lN5sT0ijgxLyDGIuQtUwLupawA=: CN=sandbox.bunq.com
    sha256/JSMzqOOrtyOT1kmau6zKhgT676hGgczD5VMdRMyJZFA=: CN=Amazon, OU=Server CA 1B, O=Amazon, C=US
    sha256/++MBgDH5WGvL9Bcn5Be30cRcL0f5O+NyoXuWtQdX1aI=: CN=Amazon Root CA 1, O=Amazon, C=US
    sha256/KwccWaCgrnaw6tsrrSO61FgLacNgG2MMLq8GE6+oP5I=: CN=Starfield Services Root Certificate Authority - G2, O="Starfield Technologies, Inc.", L=Scottsdale, ST=Arizona, C=US
  Pinned certificates for public-api.sandbox.bunq.com:
    sha256/GhNvDokiMyXzhGft+xXWFGchUmmh8R5dQEnO4xu81NY=".
	at com.bunq.sdk.http.ApiClient.get(ApiClient.java:442)
	at com.bunq.sdk.model.generated.endpoint.User.list(User.java:79)
	at com.bunq.sdk.model.generated.endpoint.User.list(User.java:85)
	at com.bunq.sdk.context.UserContext.<init>(UserContext.java:29)
	at com.bunq.sdk.context.BunqContext.loadApiContext(BunqContext.java:18)
	at com.bunq.tinker.libs.BunqLib.setupContext(BunqLib.java:101)
	at com.bunq.tinker.libs.BunqLib.<init>(BunqLib.java:79)
	at com.bunq.tinker.UserOverview.run(UserOverview.java:26)
	at com.bunq.tinker.utils.TinkerRunner.main(TinkerRunner.java:21)

I use a fresh install of the tinker_java app.

> java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

**Comment by kojoru** [comment]
@lvonk fixed by updating the SDK to the latest version.

**Comment by lvonk** [comment]
Hi,

I am getting this error again with a fresh install:

➜ java -version
java version "14" 2020-03-17
Java(TM) SE Runtime Environment (build 14+36-1461)
Java HotSpot(TM) 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

tinker on master [?] 
➜ java -jar tinker/tinker.jar UserOverview

Exception in thread "main" com.bunq.sdk.exception.UncaughtExceptionError: Uncaught exception "Certificate pinning failure!
  Peer certificate chain:
    sha256/SEJfjAW74vHQmGe/lb9NwBjzAw5y7rpJH3UWpGE5q8A=: CN=sandbox.bunq.com
    sha256/JSMzqOOrtyOT1kmau6zKhgT676hGgczD5VMdRMyJZFA=: CN=Amazon, OU=Server CA 1B, O=Amazon, C=US
    sha256/++MBgDH5WGvL9Bcn5Be30cRcL0f5O+NyoXuWtQdX1aI=: CN=Amazon Root CA 1, O=Amazon, C=US
  Pinned certificates for public-api.sandbox.bunq.com:
    sha256/9Y+oZve6H+r17Kdn+lN5sT0ijgxLyDGIuQtUwLupawA=".
	at com.bunq.sdk.http.ApiClient.post(ApiClient.java:189)
	at com.bunq.sdk.model.core.Installation.create(Installation.java:45)
	at com.bunq.sdk.context.ApiContext.initializeInstallation(ApiContext.java:233)
	at com.bunq.sdk.context.ApiContext.initialize(ApiContext.java:223)
	at com.bunq.sdk.context.ApiContext.create(ApiContext.java:140)
	at com.bunq.sdk.context.ApiContext.create(ApiContext.java:122)
	at com.bunq.sdk.context.ApiContext.create(ApiContext.java:114)
	at com.bunq.tinker.libs.BunqLib.setupContext(BunqLib.java:116)
	at com.bunq.tinker.libs.BunqLib.setupContext(BunqLib.java:106)
	at com.bunq.tinker.libs.BunqLib.<init>(BunqLib.java:98)
	at com.bunq.tinker.UserOverview.run(UserOverview.java:26)
	at com.bunq.tinker.utils.TinkerRunner.main(TinkerRunner.java:22)

**Comment by FNG21** [comment]
Hi there @lvonk! Thank you for bringing this up!

We always want you to be able to create the coolest new applications using our SDK and API. Therefore we just updated our SDK and Tinker packages to contain the newest certificate hash. You can now continue using our great API to build new awesome applications :)
